// <auto-generated />
using GreenCoinHealth.Server.Models;
using GreenCoinHealth.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GreenCoinHealth.Server.Migrations
{
    [DbContext(typeof(GreenCoinHealthContext))]
    [Migration("20240421220449_Inicial1")]
    partial class Inicial1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("GreenCoinHealth.Models.Alimentos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EsOrganico")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Precio")
                        .HasColumnType("float");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Alimentos");
                });

            modelBuilder.Entity("GreenCoinHealth.Models.Dieta", b =>
                {
                    b.Property<int>("DietaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DietaId"), 1L, 1);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DietaId");

                    b.ToTable("Dietas");
                });

            modelBuilder.Entity("GreenCoinHealth.Models.DietaAlimento", b =>
                {
                    b.Property<int>("DietaId")
                        .HasColumnType("int");

                    b.Property<int>("AlimentoId")
                        .HasColumnType("int");

                    b.HasKey("DietaId", "AlimentoId");

                    b.HasIndex("AlimentoId");

                    b.ToTable("DietaAlimentos");
                });

            modelBuilder.Entity("GreenCoinHealth.Models.Dificultad", b =>
                {
                    b.Property<int>("DificultadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DificultadId"), 1L, 1);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DificultadId");

                    b.ToTable("Dificultades");
                });

            modelBuilder.Entity("GreenCoinHealth.Models.Ejercicio", b =>
                {
                    b.Property<int>("EjercicioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EjercicioId"), 1L, 1);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DificultadId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Repeticiones")
                        .HasColumnType("int");

                    b.Property<int>("RutinaId")
                        .HasColumnType("int");

                    b.Property<int>("Series")
                        .HasColumnType("int");

                    b.HasKey("EjercicioId");

                    b.HasIndex("DificultadId");

                    b.HasIndex("RutinaId");

                    b.ToTable("Ejercicios");
                });

            modelBuilder.Entity("GreenCoinHealth.Models.Gender", b =>
                {
                    b.Property<string>("IdGender")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Id_Gender");

                    b.Property<string>("NameGender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name_Gender");

                    b.HasKey("IdGender");

                    b.ToTable("Gender", (string)null);
                });

            modelBuilder.Entity("GreenCoinHealth.Models.Role", b =>
                {
                    b.Property<string>("IdRole")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Id_Role");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdRole");

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("GreenCoinHealth.Models.Rutina", b =>
                {
                    b.Property<int>("RutinaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RutinaId"), 1L, 1);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RutinaId");

                    b.ToTable("Rutinas");
                });

            modelBuilder.Entity("GreenCoinHealth.Models.User", b =>
                {
                    b.Property<string>("Dni")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdGender")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Id_Gender");

                    b.Property<string>("IdRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Id_Role");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("TypeDni")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("username");

                    b.HasKey("Dni");

                    b.HasIndex(new[] { "IdGender" }, "IX_User_Id_Gender");

                    b.HasIndex(new[] { "IdRole" }, "IX_User_Id_Role");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("GreenCoinHealth.Models.DietaAlimento", b =>
                {
                    b.HasOne("GreenCoinHealth.Models.Alimentos", "Alimento")
                        .WithMany()
                        .HasForeignKey("AlimentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GreenCoinHealth.Models.Dieta", "Dieta")
                        .WithMany("DietaAlimentos")
                        .HasForeignKey("DietaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alimento");

                    b.Navigation("Dieta");
                });

            modelBuilder.Entity("GreenCoinHealth.Models.Ejercicio", b =>
                {
                    b.HasOne("GreenCoinHealth.Models.Dificultad", "Dificultad")
                        .WithMany()
                        .HasForeignKey("DificultadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GreenCoinHealth.Models.Rutina", "Rutina")
                        .WithMany("Ejercicios")
                        .HasForeignKey("RutinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dificultad");

                    b.Navigation("Rutina");
                });

            modelBuilder.Entity("GreenCoinHealth.Models.User", b =>
                {
                    b.HasOne("GreenCoinHealth.Models.Gender", "IdGenderNavigation")
                        .WithMany("Users")
                        .HasForeignKey("IdGender")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GreenCoinHealth.Models.Role", "IdRoleNavigation")
                        .WithMany("Users")
                        .HasForeignKey("IdRole")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdGenderNavigation");

                    b.Navigation("IdRoleNavigation");
                });

            modelBuilder.Entity("GreenCoinHealth.Models.Dieta", b =>
                {
                    b.Navigation("DietaAlimentos");
                });

            modelBuilder.Entity("GreenCoinHealth.Models.Gender", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("GreenCoinHealth.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("GreenCoinHealth.Models.Rutina", b =>
                {
                    b.Navigation("Ejercicios");
                });
#pragma warning restore 612, 618
        }
    }
}
